version: "3.8"

services:
  webdav:
    build: ./build/webdav/
    command: ./entrypoint.sh
    environment:
      NGINX_CRT_FILE: /run/secrets/server_crt
      NGINX_KEY_FILE: /run/secrets/server_key
      WEBDAV_USERNAME_FILE: /run/secrets/webdav_username
      WEBDAV_PASSWORD_FILE: /run/secrets/webdav_password
    secrets:
      - server_crt
      - server_key
      - webdav_username
      - webdav_password
    volumes:
      - ./data/joplin:/server/files
    ports:
      - 8443:443

  gitsync:
    build: ./build/gitsync/
    command: ./entrypoint.sh
    environment:
      GIT_KEY_FILE: /run/secrets/git_key
      GIT_PUB_FILE: /run/secrets/git_pub
    secrets:
      - git_pub
      - git_key
    volumes:
      - ./data:/gitsync/repo:ro

secrets:
  webdav_username:
    file: ./secrets/webdav_username.txt
  webdav_password:
    file: ./secrets/webdav_password.txt
  server_key:
    file: ./secrets/server.key
  server_crt:
    file: ./secrets/server.crt
  git_key:
    file: ./secrets/git.key
  git_pub:
    file: ./secrets/git.pub
